# Travis CI 자동 실행 스크립트 생성

language: java
jdk:
  - openjdk11
branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_15887e653782_key -iv $encrypted_15887e653782_iv -in application-real-db.properties.enc -out src/main/resources/application-real-db.properties -d
  - openssl aes-256-cbc -K $encrypted_404881035eff_key -iv $encrypted_404881035eff_iv -in application-oauth.properties.enc -out src/main/resources/application-oauth.properties -d

script: "./gradlew --stacktrace clean build"

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: fsw-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - tommarow@naver.com