version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes
# CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# CodeDeploy배포 단계에서 실행할 명령어를 지정
# ApplicationStart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 한다.
# timeout: 60으로 스크립트 실행 60초 이상 수행되면 실패(무한정 대기 방지)
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user