version: 0.0
os: linux
# step3 : destination step2 -> step3
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes
# CodeDeploy에서 EC2서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
# CodeDeploy배포 단계에서 실행할 명령어를 지정
# ApplicationStart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 한다.
# timeout: 60으로 스크립트 실행 60초 이상 수행되면 실패(무한정 대기 방지)
# step3 : AfterInstall, ValidateService추가, ApplicationStart 수정
hooks:
  AfterInstall:
    - location: stop.sh # nginx와 연결되어 있지 않은 springboot 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start.sh # step3 : deploy.sh -> start.sh 변경, nginx와 연결되어 있지 않은 Port로 새 버전의 springboot 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # springboot가 정상적으로 실행되었는지 확인
      timeout: 60
      runas: ec2-user